version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - app/.env
    environment:
      - DB_HOST=db
      - DB_NAME=REST
      - DB_USER=postgres
      - DB_PASS=22081998
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - app/.env
    environment:
      - POSTGRES_DB=REST
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=22081998

volumes:
  dev-db-data:
  dev-static-data:

